///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace DrBaras_Test
{
    public partial class BookAppointment
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }
        
        public void ClickNextButton()
        {
        	if(repo.ApplicationUnderTest.BookAppointment.btnNextInfo.Exists(2000))
        	{
        		WebElement btnNext = repo.ApplicationUnderTest.BookAppointment.btnNext.FindSingle(".//button[#'request_a_call_btn']");
        		btnNext.Click();
        		Ranorex.Report.Info("The user entered the personal details and clicking on the next button");
        	}
        }
        
        public void SelectClinic(string clickplace)
        {
        	       	
        	SelectTag city = repo.ApplicationUnderTest.BookAppointment.AppointmentOpt.SelectClinic;
        	OptionTag ClinicLocation = city.FindSingle(".//option[@value='"+clickplace+"']");
        	ClinicLocation.Selected =true;
        }
        
        public void SelectAppTime(string AppTime)
        {
        	Ranorex.Delay.Seconds(1);
        	OptionTag apptime = repo.ApplicationUnderTest.BookAppointment.AppointmentOpt.AppointMentTime.FindSingle(".//option[@value='"+AppTime+"']");
        	apptime.Selected=true;
        }
        
        public void selectPaytype()
        {
        	OptionTag PayType = repo.ApplicationUnderTest.BookAppointment.AppointmentOpt.PayentTtype.FindSingle(".//option[@value='CC-199']");
        	PayType.Selected=true;
        }
        
        public void ClickConfApp()
        {
        	if(repo.ApplicationUnderTest.BookAppointment.AppointmentOpt.btn_confAppInfo.Exists(2000))
        	{
        		WebElement btnconf = repo.ApplicationUnderTest.BookAppointment.AppointmentOpt.btn_confApp.FindSingle(".//button[@id='book-an-appointment-sectwo']");
        		btnconf.Click();
        		Ranorex.Report.Info("The user selected the appointment details and clicked on the confirm appointment button");
        	}
        }

        public void SelectAppTime()
        {
            // TODO: Replace the following line with your code implementation.
            throw new NotImplementedException();
        }

    }
}
