///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace DrBaras_Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the DrBaras_TestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("f10252fb-1daf-408e-acf4-e80c220d5cb8")]
    public partial class DrBaras_TestRepository : RepoGenBaseFolder
    {
        static DrBaras_TestRepository instance = new DrBaras_TestRepository();
        DrBaras_TestRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;

        /// <summary>
        /// Gets the singleton class instance representing the DrBaras_TestRepository element repository.
        /// </summary>
        [RepositoryFolder("f10252fb-1daf-408e-acf4-e80c220d5cb8")]
        public static DrBaras_TestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public DrBaras_TestRepository() 
            : base("DrBaras_TestRepository", "/", null, 0, false, "f10252fb-1daf-408e-acf4-e80c220d5cb8", ".\\RepositoryImages\\DrBaras_TestRepositoryf10252fb.rximgres")
        {
            _applicationundertest = new DrBaras_TestRepositoryFolders.ApplicationUnderTestAppFolder(this);
        }

#region Variables

        string _City = "AGRA";

        /// <summary>
        /// Gets or sets the value of variable City.
        /// </summary>
        [TestVariable("e9545214-4fac-4d7a-afa1-da4c7236d295")]
        public string City
        {
            get { return _City; }
            set { _City = value; }
        }

        string _ClincPlace = "M G ROAD AGRA";

        /// <summary>
        /// Gets or sets the value of variable ClincPlace.
        /// </summary>
        [TestVariable("2d3f846d-5432-46b6-91d8-315d722a3469")]
        public string ClincPlace
        {
            get { return _ClincPlace; }
            set { _ClincPlace = value; }
        }

        string _AppTime = "4:00PM-5:00PM";

        /// <summary>
        /// Gets or sets the value of variable AppTime.
        /// </summary>
        [TestVariable("99558a7c-a91a-4b7b-9452-5516d7f65682")]
        public string AppTime
        {
            get { return _AppTime; }
            set { _AppTime = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("f10252fb-1daf-408e-acf4-e80c220d5cb8")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("4c402124-2d38-484d-9b7b-48102a69424e")]
        public virtual DrBaras_TestRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class DrBaras_TestRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("4c402124-2d38-484d-9b7b-48102a69424e")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            DrBaras_TestRepositoryFolders.HomePageFolder _homepage;
            DrBaras_TestRepositoryFolders.ChatWindowFolder _chatwindow;
            DrBaras_TestRepositoryFolders.ChatBoxFolder _chatbox;
            DrBaras_TestRepositoryFolders.BookAppointmentFolder _bookappointment;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.drbatras.com']", parentFolder, 30000, null, false, "4c402124-2d38-484d-9b7b-48102a69424e", "")
            {
                _homepage = new DrBaras_TestRepositoryFolders.HomePageFolder(this);
                _chatwindow = new DrBaras_TestRepositoryFolders.ChatWindowFolder(this);
                _chatbox = new DrBaras_TestRepositoryFolders.ChatBoxFolder(this);
                _bookappointment = new DrBaras_TestRepositoryFolders.BookAppointmentFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4c402124-2d38-484d-9b7b-48102a69424e")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4c402124-2d38-484d-9b7b-48102a69424e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The HomePage folder.
            /// </summary>
            [RepositoryFolder("a09114f6-ae54-4b4c-8617-663e4652fcc8")]
            public virtual DrBaras_TestRepositoryFolders.HomePageFolder HomePage
            {
                get { return _homepage; }
            }

            /// <summary>
            /// The ChatWindow folder.
            /// </summary>
            [RepositoryFolder("e5e3e3fa-689a-406f-93c6-3cb29865010a")]
            public virtual DrBaras_TestRepositoryFolders.ChatWindowFolder ChatWindow
            {
                get { return _chatwindow; }
            }

            /// <summary>
            /// The ChatBox folder.
            /// </summary>
            [RepositoryFolder("c515739c-9ef4-4ee0-9275-b8e71a2a49eb")]
            public virtual DrBaras_TestRepositoryFolders.ChatBoxFolder ChatBox
            {
                get { return _chatbox; }
            }

            /// <summary>
            /// The BookAppointment folder.
            /// </summary>
            [RepositoryFolder("5af3c6e3-8812-4df6-b249-0e5730e6d076")]
            public virtual DrBaras_TestRepositoryFolders.BookAppointmentFolder BookAppointment
            {
                get { return _bookappointment; }
            }
        }

        /// <summary>
        /// The HomePageFolder folder.
        /// </summary>
        [RepositoryFolder("a09114f6-ae54-4b4c-8617-663e4652fcc8")]
        public partial class HomePageFolder : RepoGenBaseFolder
        {
            DrBaras_TestRepositoryFolders.UIListFolder _uilist;
            RepoItemInfo _clinic_logoInfo;
            RepoItemInfo _link_treatmentsInfo;
            RepoItemInfo _link_childhealthInfo;
            RepoItemInfo _link_immunityInfo;

            /// <summary>
            /// Creates a new HomePage  folder.
            /// </summary>
            public HomePageFolder(RepoGenBaseFolder parentFolder) :
                    base("HomePage", "", parentFolder, 0, null, false, "a09114f6-ae54-4b4c-8617-663e4652fcc8", "")
            {
                _uilist = new DrBaras_TestRepositoryFolders.UIListFolder(this);
                _clinic_logoInfo = new RepoItemInfo(this, "clinic_Logo", ".//img[@alt='Dr Batra''s Homeopathy clinic']", "", 30000, null, "bfee5f60-88f4-42a4-8de7-53c7c334358b");
                _link_treatmentsInfo = new RepoItemInfo(this, "link_Treatments", ".//a[@innertext='TREATMENTS']", "", 30000, null, "20745bf5-656a-46f0-b4e6-94b8e3df0820");
                _link_childhealthInfo = new RepoItemInfo(this, "Link_Childhealth", ".//a[@innertext='Child Health']", "", 30000, null, "300856b0-3289-4910-8f02-e0e19668cb3d");
                _link_immunityInfo = new RepoItemInfo(this, "link_Immunity", ".//a[@innertext='Immunity']", "", 30000, null, "37f9caa0-4805-4806-bc5b-2f28cc9ac015");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a09114f6-ae54-4b4c-8617-663e4652fcc8")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The clinic_Logo item.
            /// </summary>
            [RepositoryItem("bfee5f60-88f4-42a4-8de7-53c7c334358b")]
            public virtual Ranorex.ImgTag clinic_Logo
            {
                get
                {
                    return _clinic_logoInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The clinic_Logo item info.
            /// </summary>
            [RepositoryItemInfo("bfee5f60-88f4-42a4-8de7-53c7c334358b")]
            public virtual RepoItemInfo clinic_LogoInfo
            {
                get
                {
                    return _clinic_logoInfo;
                }
            }

            /// <summary>
            /// The link_Treatments item.
            /// </summary>
            [RepositoryItem("20745bf5-656a-46f0-b4e6-94b8e3df0820")]
            public virtual Ranorex.ATag link_Treatments
            {
                get
                {
                    return _link_treatmentsInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The link_Treatments item info.
            /// </summary>
            [RepositoryItemInfo("20745bf5-656a-46f0-b4e6-94b8e3df0820")]
            public virtual RepoItemInfo link_TreatmentsInfo
            {
                get
                {
                    return _link_treatmentsInfo;
                }
            }

            /// <summary>
            /// The Link_Childhealth item.
            /// </summary>
            [RepositoryItem("300856b0-3289-4910-8f02-e0e19668cb3d")]
            public virtual Ranorex.ATag Link_Childhealth
            {
                get
                {
                    return _link_childhealthInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Link_Childhealth item info.
            /// </summary>
            [RepositoryItemInfo("300856b0-3289-4910-8f02-e0e19668cb3d")]
            public virtual RepoItemInfo Link_ChildhealthInfo
            {
                get
                {
                    return _link_childhealthInfo;
                }
            }

            /// <summary>
            /// The link_Immunity item.
            /// </summary>
            [RepositoryItem("37f9caa0-4805-4806-bc5b-2f28cc9ac015")]
            public virtual Ranorex.ATag link_Immunity
            {
                get
                {
                    return _link_immunityInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The link_Immunity item info.
            /// </summary>
            [RepositoryItemInfo("37f9caa0-4805-4806-bc5b-2f28cc9ac015")]
            public virtual RepoItemInfo link_ImmunityInfo
            {
                get
                {
                    return _link_immunityInfo;
                }
            }

            /// <summary>
            /// The UIList folder.
            /// </summary>
            [RepositoryFolder("c4da53ae-0baf-4cfb-ad21-278af7a16366")]
            public virtual DrBaras_TestRepositoryFolders.UIListFolder UIList
            {
                get { return _uilist; }
            }
        }

        /// <summary>
        /// The UIListFolder folder.
        /// </summary>
        [RepositoryFolder("c4da53ae-0baf-4cfb-ad21-278af7a16366")]
        public partial class UIListFolder : RepoGenBaseFolder
        {
            DrBaras_TestRepositoryFolders.SubmenuFolder _submenu;
            RepoItemInfo _linkchInfo;

            /// <summary>
            /// Creates a new UIList  folder.
            /// </summary>
            public UIListFolder(RepoGenBaseFolder parentFolder) :
                    base("UIList", ".//ul[@class='nav flex-column' and @visible='True']", parentFolder, 30000, null, false, "c4da53ae-0baf-4cfb-ad21-278af7a16366", "")
            {
                _submenu = new DrBaras_TestRepositoryFolders.SubmenuFolder(this);
                _linkchInfo = new RepoItemInfo(this, "LinkCh", ".//a[@innertext='Child Health']", "", 30000, null, "9bad5e54-258a-43ea-9689-14535775097e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c4da53ae-0baf-4cfb-ad21-278af7a16366")]
            public virtual Ranorex.UlTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.UlTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c4da53ae-0baf-4cfb-ad21-278af7a16366")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LinkCh item.
            /// </summary>
            [RepositoryItem("9bad5e54-258a-43ea-9689-14535775097e")]
            public virtual Ranorex.ATag LinkCh
            {
                get
                {
                    return _linkchInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The LinkCh item info.
            /// </summary>
            [RepositoryItemInfo("9bad5e54-258a-43ea-9689-14535775097e")]
            public virtual RepoItemInfo LinkChInfo
            {
                get
                {
                    return _linkchInfo;
                }
            }

            /// <summary>
            /// The Submenu folder.
            /// </summary>
            [RepositoryFolder("489cf43b-03fd-4b5d-bcc1-07d972fc3f80")]
            public virtual DrBaras_TestRepositoryFolders.SubmenuFolder Submenu
            {
                get { return _submenu; }
            }
        }

        /// <summary>
        /// The SubmenuFolder folder.
        /// </summary>
        [RepositoryFolder("489cf43b-03fd-4b5d-bcc1-07d972fc3f80")]
        public partial class SubmenuFolder : RepoGenBaseFolder
        {
            RepoItemInfo _link_immunityInfo;

            /// <summary>
            /// Creates a new Submenu  folder.
            /// </summary>
            public SubmenuFolder(RepoGenBaseFolder parentFolder) :
                    base("Submenu", ".//div[@id='menutab-5']", parentFolder, 30000, null, false, "489cf43b-03fd-4b5d-bcc1-07d972fc3f80", "")
            {
                _link_immunityInfo = new RepoItemInfo(this, "Link_Immunity", ".//a[@innertext='Immunity']", "", 30000, null, "05526325-49fe-45ee-be5b-6da18ecccbcc");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("489cf43b-03fd-4b5d-bcc1-07d972fc3f80")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("489cf43b-03fd-4b5d-bcc1-07d972fc3f80")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Link_Immunity item.
            /// </summary>
            [RepositoryItem("05526325-49fe-45ee-be5b-6da18ecccbcc")]
            public virtual Ranorex.ATag Link_Immunity
            {
                get
                {
                    return _link_immunityInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Link_Immunity item info.
            /// </summary>
            [RepositoryItemInfo("05526325-49fe-45ee-be5b-6da18ecccbcc")]
            public virtual RepoItemInfo Link_ImmunityInfo
            {
                get
                {
                    return _link_immunityInfo;
                }
            }
        }

        /// <summary>
        /// The ChatWindowFolder folder.
        /// </summary>
        [RepositoryFolder("e5e3e3fa-689a-406f-93c6-3cb29865010a")]
        public partial class ChatWindowFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btn_chatnowInfo;

            /// <summary>
            /// Creates a new ChatWindow  folder.
            /// </summary>
            public ChatWindowFolder(RepoGenBaseFolder parentFolder) :
                    base("ChatWindow", ".//div[#'kenytChatBubble']", parentFolder, 30000, null, false, "e5e3e3fa-689a-406f-93c6-3cb29865010a", "")
            {
                _btn_chatnowInfo = new RepoItemInfo(this, "btn_chatNow", ".//button[@id='chatNowBtn']", "", 30000, null, "50e67030-0a34-4304-9a3b-7f0c42e6b3d5");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e5e3e3fa-689a-406f-93c6-3cb29865010a")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e5e3e3fa-689a-406f-93c6-3cb29865010a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btn_chatNow item.
            /// </summary>
            [RepositoryItem("50e67030-0a34-4304-9a3b-7f0c42e6b3d5")]
            public virtual Ranorex.Button btn_chatNow
            {
                get
                {
                    return _btn_chatnowInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btn_chatNow item info.
            /// </summary>
            [RepositoryItemInfo("50e67030-0a34-4304-9a3b-7f0c42e6b3d5")]
            public virtual RepoItemInfo btn_chatNowInfo
            {
                get
                {
                    return _btn_chatnowInfo;
                }
            }
        }

        /// <summary>
        /// The ChatBoxFolder folder.
        /// </summary>
        [RepositoryFolder("c515739c-9ef4-4ee0-9275-b8e71a2a49eb")]
        public partial class ChatBoxFolder : RepoGenBaseFolder
        {
            RepoItemInfo _closebtnInfo;

            /// <summary>
            /// Creates a new ChatBox  folder.
            /// </summary>
            public ChatBoxFolder(RepoGenBaseFolder parentFolder) :
                    base("ChatBox", ".//div[#'chatbox-container']", parentFolder, 30000, null, false, "c515739c-9ef4-4ee0-9275-b8e71a2a49eb", "")
            {
                _closebtnInfo = new RepoItemInfo(this, "CloseBtn", ".//span[@innertext='close']", "", 30000, null, "e60a60fd-55a7-4527-80c2-22c57c1e0687");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c515739c-9ef4-4ee0-9275-b8e71a2a49eb")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c515739c-9ef4-4ee0-9275-b8e71a2a49eb")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CloseBtn item.
            /// </summary>
            [RepositoryItem("e60a60fd-55a7-4527-80c2-22c57c1e0687")]
            public virtual Ranorex.SpanTag CloseBtn
            {
                get
                {
                    return _closebtnInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The CloseBtn item info.
            /// </summary>
            [RepositoryItemInfo("e60a60fd-55a7-4527-80c2-22c57c1e0687")]
            public virtual RepoItemInfo CloseBtnInfo
            {
                get
                {
                    return _closebtnInfo;
                }
            }
        }

        /// <summary>
        /// The BookAppointmentFolder folder.
        /// </summary>
        [RepositoryFolder("5af3c6e3-8812-4df6-b249-0e5730e6d076")]
        public partial class BookAppointmentFolder : RepoGenBaseFolder
        {
            DrBaras_TestRepositoryFolders.AppointmentOptFolder _appointmentopt;
            RepoItemInfo _btn_consultnowInfo;
            RepoItemInfo _header_bookdocconsultInfo;
            RepoItemInfo _textbox_nameInfo;
            RepoItemInfo _textbox_phoneInfo;
            RepoItemInfo _textbox_emailInfo;
            RepoItemInfo _checkbox_tandcInfo;
            RepoItemInfo _btnnextInfo;

            /// <summary>
            /// Creates a new BookAppointment  folder.
            /// </summary>
            public BookAppointmentFolder(RepoGenBaseFolder parentFolder) :
                    base("BookAppointment", "", parentFolder, 0, null, false, "5af3c6e3-8812-4df6-b249-0e5730e6d076", "")
            {
                _appointmentopt = new DrBaras_TestRepositoryFolders.AppointmentOptFolder(this);
                _btn_consultnowInfo = new RepoItemInfo(this, "btn_Consultnow", ".//a[@innertext='CONSULT NOW']", "", 30000, null, "88456318-efd5-4033-953e-21af370e6ea2");
                _header_bookdocconsultInfo = new RepoItemInfo(this, "header_BookDocConsult", ".//h2[@innertext='Book a Doctor Consultation now just at ']", "", 30000, null, "4d5e1120-1c27-4ed7-bc23-2863514586f3");
                _textbox_nameInfo = new RepoItemInfo(this, "textbox_Name", ".//input[@id='request_name']", "", 30000, null, "84d6acef-8491-4c66-9edc-63286f419807");
                _textbox_phoneInfo = new RepoItemInfo(this, "textbox_Phone", ".//input[@id='request_contact_no']", "", 30000, null, "79e59d65-1242-4a71-bc2c-0bc0f8d4e374");
                _textbox_emailInfo = new RepoItemInfo(this, "textbox_email", ".//input[@id='request_email']", "", 30000, null, "9e5e8882-d55e-4eed-992b-45de928fec7c");
                _checkbox_tandcInfo = new RepoItemInfo(this, "checkbox_TandC", ".//input[@id='terms_and_conditions_chk']", "", 30000, null, "cc1f745b-acb0-457b-9693-77c7823d0add");
                _btnnextInfo = new RepoItemInfo(this, "btnNext", ".//div[8]/div[@class='col-12']", "", 30000, null, "df676fbc-101b-4c32-8a33-20285fd2d464");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5af3c6e3-8812-4df6-b249-0e5730e6d076")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btn_Consultnow item.
            /// </summary>
            [RepositoryItem("88456318-efd5-4033-953e-21af370e6ea2")]
            public virtual Ranorex.ATag btn_Consultnow
            {
                get
                {
                    return _btn_consultnowInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The btn_Consultnow item info.
            /// </summary>
            [RepositoryItemInfo("88456318-efd5-4033-953e-21af370e6ea2")]
            public virtual RepoItemInfo btn_ConsultnowInfo
            {
                get
                {
                    return _btn_consultnowInfo;
                }
            }

            /// <summary>
            /// The header_BookDocConsult item.
            /// </summary>
            [RepositoryItem("4d5e1120-1c27-4ed7-bc23-2863514586f3")]
            public virtual Ranorex.H2Tag header_BookDocConsult
            {
                get
                {
                    return _header_bookdocconsultInfo.CreateAdapter<Ranorex.H2Tag>(true);
                }
            }

            /// <summary>
            /// The header_BookDocConsult item info.
            /// </summary>
            [RepositoryItemInfo("4d5e1120-1c27-4ed7-bc23-2863514586f3")]
            public virtual RepoItemInfo header_BookDocConsultInfo
            {
                get
                {
                    return _header_bookdocconsultInfo;
                }
            }

            /// <summary>
            /// The textbox_Name item.
            /// </summary>
            [RepositoryItem("84d6acef-8491-4c66-9edc-63286f419807")]
            public virtual Ranorex.InputTag textbox_Name
            {
                get
                {
                    return _textbox_nameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The textbox_Name item info.
            /// </summary>
            [RepositoryItemInfo("84d6acef-8491-4c66-9edc-63286f419807")]
            public virtual RepoItemInfo textbox_NameInfo
            {
                get
                {
                    return _textbox_nameInfo;
                }
            }

            /// <summary>
            /// The textbox_Phone item.
            /// </summary>
            [RepositoryItem("79e59d65-1242-4a71-bc2c-0bc0f8d4e374")]
            public virtual Ranorex.InputTag textbox_Phone
            {
                get
                {
                    return _textbox_phoneInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The textbox_Phone item info.
            /// </summary>
            [RepositoryItemInfo("79e59d65-1242-4a71-bc2c-0bc0f8d4e374")]
            public virtual RepoItemInfo textbox_PhoneInfo
            {
                get
                {
                    return _textbox_phoneInfo;
                }
            }

            /// <summary>
            /// The textbox_email item.
            /// </summary>
            [RepositoryItem("9e5e8882-d55e-4eed-992b-45de928fec7c")]
            public virtual Ranorex.InputTag textbox_email
            {
                get
                {
                    return _textbox_emailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The textbox_email item info.
            /// </summary>
            [RepositoryItemInfo("9e5e8882-d55e-4eed-992b-45de928fec7c")]
            public virtual RepoItemInfo textbox_emailInfo
            {
                get
                {
                    return _textbox_emailInfo;
                }
            }

            /// <summary>
            /// The checkbox_TandC item.
            /// </summary>
            [RepositoryItem("cc1f745b-acb0-457b-9693-77c7823d0add")]
            public virtual Ranorex.InputTag checkbox_TandC
            {
                get
                {
                    return _checkbox_tandcInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The checkbox_TandC item info.
            /// </summary>
            [RepositoryItemInfo("cc1f745b-acb0-457b-9693-77c7823d0add")]
            public virtual RepoItemInfo checkbox_TandCInfo
            {
                get
                {
                    return _checkbox_tandcInfo;
                }
            }

            /// <summary>
            /// The btnNext item.
            /// </summary>
            [RepositoryItem("df676fbc-101b-4c32-8a33-20285fd2d464")]
            public virtual Ranorex.DivTag btnNext
            {
                get
                {
                    return _btnnextInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The btnNext item info.
            /// </summary>
            [RepositoryItemInfo("df676fbc-101b-4c32-8a33-20285fd2d464")]
            public virtual RepoItemInfo btnNextInfo
            {
                get
                {
                    return _btnnextInfo;
                }
            }

            /// <summary>
            /// The AppointmentOpt folder.
            /// </summary>
            [RepositoryFolder("003f6747-7253-4fab-968c-bf19fca54b24")]
            public virtual DrBaras_TestRepositoryFolders.AppointmentOptFolder AppointmentOpt
            {
                get { return _appointmentopt; }
            }
        }

        /// <summary>
        /// The AppointmentOptFolder folder.
        /// </summary>
        [RepositoryFolder("003f6747-7253-4fab-968c-bf19fca54b24")]
        public partial class AppointmentOptFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selectcityInfo;
            RepoItemInfo _cityddInfo;
            RepoItemInfo _selectclinicInfo;
            RepoItemInfo _clinicddInfo;
            RepoItemInfo _appointmentdayInfo;
            RepoItemInfo _appointmenttimeInfo;
            RepoItemInfo _appointmenttime_ddInfo;
            RepoItemInfo _payentttypeInfo;
            RepoItemInfo _payentttype_valueInfo;
            RepoItemInfo _appconfirmationInfo;
            RepoItemInfo _btn_confappInfo;

            /// <summary>
            /// Creates a new AppointmentOpt  folder.
            /// </summary>
            public AppointmentOptFolder(RepoGenBaseFolder parentFolder) :
                    base("AppointmentOpt", "", parentFolder, 0, null, false, "003f6747-7253-4fab-968c-bf19fca54b24", "")
            {
                _selectcityInfo = new RepoItemInfo(this, "SelectCity", ".//span[@title='Select City']", "", 30000, null, "994312ba-7cdf-4a2c-97a5-4af4eede512f");
                _cityddInfo = new RepoItemInfo(this, "CityDD", ".//ul[@id='select2-city_tmp-results']/li[@innertext=$City]", "", 30000, null, "5ff0278b-3269-484d-8c25-beb1c42e82f4");
                _selectclinicInfo = new RepoItemInfo(this, "SelectClinic", ".//select[@id='clinic_tmp']", "", 30000, null, "24831630-579a-4c06-b56e-2d6babe75ad7");
                _clinicddInfo = new RepoItemInfo(this, "ClinicDD", ".//select[@id='clinic_tmp']/option[@innertext=$ClincPlace]", "", 30000, null, "a3c59f3f-eb27-45fa-8da7-b12b4756295a");
                _appointmentdayInfo = new RepoItemInfo(this, "AppointMentDay", ".//input[@id='day_tmp']", "", 30000, null, "4aa19375-8978-488b-8ff2-72f1bb0108ae");
                _appointmenttimeInfo = new RepoItemInfo(this, "AppointMentTime", ".//select[#'time_tmp']", "", 30000, null, "debd2724-5b14-42af-b65e-5f917fc9eacd");
                _appointmenttime_ddInfo = new RepoItemInfo(this, "AppointMentTime_DD", ".//select[#'time_tmp']/option[@innertext~'10' and @visible=@true]", "", 30000, null, "6cad8915-dd28-4877-9aec-7b1c860a8f96");
                _payentttypeInfo = new RepoItemInfo(this, "PayentTtype", ".//select[#'payment_type']", "", 30000, null, "91f5744a-9a80-40eb-bb84-d988c5ea559e");
                _payentttype_valueInfo = new RepoItemInfo(this, "PayentTtype_Value", ".//select[#'payment_type']/option[@value='CC-199']", "", 30000, null, "1db32a99-02aa-41e4-9fbe-895f740809bd");
                _appconfirmationInfo = new RepoItemInfo(this, "AppConfirmation", ".//h4[@innertext>'YOUR APPOINTMENT IS CONFI']", "", 30000, null, "5cc53363-897c-414b-a5b6-afcac08798cc");
                _btn_confappInfo = new RepoItemInfo(this, "btn_confApp", ".//div[10]/div[@class='col-12']", "", 30000, null, "edc07971-6d63-45cc-88b4-032073c75d30");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("003f6747-7253-4fab-968c-bf19fca54b24")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SelectCity item.
            /// </summary>
            [RepositoryItem("994312ba-7cdf-4a2c-97a5-4af4eede512f")]
            public virtual Ranorex.SpanTag SelectCity
            {
                get
                {
                    return _selectcityInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SelectCity item info.
            /// </summary>
            [RepositoryItemInfo("994312ba-7cdf-4a2c-97a5-4af4eede512f")]
            public virtual RepoItemInfo SelectCityInfo
            {
                get
                {
                    return _selectcityInfo;
                }
            }

            /// <summary>
            /// The CityDD item.
            /// </summary>
            [RepositoryItem("5ff0278b-3269-484d-8c25-beb1c42e82f4")]
            public virtual Ranorex.LiTag CityDD
            {
                get
                {
                    return _cityddInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The CityDD item info.
            /// </summary>
            [RepositoryItemInfo("5ff0278b-3269-484d-8c25-beb1c42e82f4")]
            public virtual RepoItemInfo CityDDInfo
            {
                get
                {
                    return _cityddInfo;
                }
            }

            /// <summary>
            /// The SelectClinic item.
            /// </summary>
            [RepositoryItem("24831630-579a-4c06-b56e-2d6babe75ad7")]
            public virtual Ranorex.SelectTag SelectClinic
            {
                get
                {
                    return _selectclinicInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The SelectClinic item info.
            /// </summary>
            [RepositoryItemInfo("24831630-579a-4c06-b56e-2d6babe75ad7")]
            public virtual RepoItemInfo SelectClinicInfo
            {
                get
                {
                    return _selectclinicInfo;
                }
            }

            /// <summary>
            /// The ClinicDD item.
            /// </summary>
            [RepositoryItem("a3c59f3f-eb27-45fa-8da7-b12b4756295a")]
            public virtual Ranorex.OptionTag ClinicDD
            {
                get
                {
                    return _clinicddInfo.CreateAdapter<Ranorex.OptionTag>(true);
                }
            }

            /// <summary>
            /// The ClinicDD item info.
            /// </summary>
            [RepositoryItemInfo("a3c59f3f-eb27-45fa-8da7-b12b4756295a")]
            public virtual RepoItemInfo ClinicDDInfo
            {
                get
                {
                    return _clinicddInfo;
                }
            }

            /// <summary>
            /// The AppointMentDay item.
            /// </summary>
            [RepositoryItem("4aa19375-8978-488b-8ff2-72f1bb0108ae")]
            public virtual Ranorex.InputTag AppointMentDay
            {
                get
                {
                    return _appointmentdayInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The AppointMentDay item info.
            /// </summary>
            [RepositoryItemInfo("4aa19375-8978-488b-8ff2-72f1bb0108ae")]
            public virtual RepoItemInfo AppointMentDayInfo
            {
                get
                {
                    return _appointmentdayInfo;
                }
            }

            /// <summary>
            /// The AppointMentTime item.
            /// </summary>
            [RepositoryItem("debd2724-5b14-42af-b65e-5f917fc9eacd")]
            public virtual Ranorex.SelectTag AppointMentTime
            {
                get
                {
                    return _appointmenttimeInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The AppointMentTime item info.
            /// </summary>
            [RepositoryItemInfo("debd2724-5b14-42af-b65e-5f917fc9eacd")]
            public virtual RepoItemInfo AppointMentTimeInfo
            {
                get
                {
                    return _appointmenttimeInfo;
                }
            }

            /// <summary>
            /// The AppointMentTime_DD item.
            /// </summary>
            [RepositoryItem("6cad8915-dd28-4877-9aec-7b1c860a8f96")]
            public virtual Ranorex.OptionTag AppointMentTime_DD
            {
                get
                {
                    return _appointmenttime_ddInfo.CreateAdapter<Ranorex.OptionTag>(true);
                }
            }

            /// <summary>
            /// The AppointMentTime_DD item info.
            /// </summary>
            [RepositoryItemInfo("6cad8915-dd28-4877-9aec-7b1c860a8f96")]
            public virtual RepoItemInfo AppointMentTime_DDInfo
            {
                get
                {
                    return _appointmenttime_ddInfo;
                }
            }

            /// <summary>
            /// The PayentTtype item.
            /// </summary>
            [RepositoryItem("91f5744a-9a80-40eb-bb84-d988c5ea559e")]
            public virtual Ranorex.SelectTag PayentTtype
            {
                get
                {
                    return _payentttypeInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The PayentTtype item info.
            /// </summary>
            [RepositoryItemInfo("91f5744a-9a80-40eb-bb84-d988c5ea559e")]
            public virtual RepoItemInfo PayentTtypeInfo
            {
                get
                {
                    return _payentttypeInfo;
                }
            }

            /// <summary>
            /// The PayentTtype_Value item.
            /// </summary>
            [RepositoryItem("1db32a99-02aa-41e4-9fbe-895f740809bd")]
            public virtual Ranorex.OptionTag PayentTtype_Value
            {
                get
                {
                    return _payentttype_valueInfo.CreateAdapter<Ranorex.OptionTag>(true);
                }
            }

            /// <summary>
            /// The PayentTtype_Value item info.
            /// </summary>
            [RepositoryItemInfo("1db32a99-02aa-41e4-9fbe-895f740809bd")]
            public virtual RepoItemInfo PayentTtype_ValueInfo
            {
                get
                {
                    return _payentttype_valueInfo;
                }
            }

            /// <summary>
            /// The AppConfirmation item.
            /// </summary>
            [RepositoryItem("5cc53363-897c-414b-a5b6-afcac08798cc")]
            public virtual Ranorex.H4Tag AppConfirmation
            {
                get
                {
                    return _appconfirmationInfo.CreateAdapter<Ranorex.H4Tag>(true);
                }
            }

            /// <summary>
            /// The AppConfirmation item info.
            /// </summary>
            [RepositoryItemInfo("5cc53363-897c-414b-a5b6-afcac08798cc")]
            public virtual RepoItemInfo AppConfirmationInfo
            {
                get
                {
                    return _appconfirmationInfo;
                }
            }

            /// <summary>
            /// The btn_confApp item.
            /// </summary>
            [RepositoryItem("edc07971-6d63-45cc-88b4-032073c75d30")]
            public virtual Ranorex.DivTag btn_confApp
            {
                get
                {
                    return _btn_confappInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The btn_confApp item info.
            /// </summary>
            [RepositoryItemInfo("edc07971-6d63-45cc-88b4-032073c75d30")]
            public virtual RepoItemInfo btn_confAppInfo
            {
                get
                {
                    return _btn_confappInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
